-- MySQL Script generated by MySQL Workbench
-- Thu May 11 19:19:22 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema proyectodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyectodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyectodb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  `Imagen` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `proyectodb` ;

-- -----------------------------------------------------
-- Table `proyectodb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectodb`.`usuarios` (
  `idUsuarios` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Contrasena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `proyectodb` ;

-- -----------------------------------------------------
-- procedure InsertarUsuario
-- -----------------------------------------------------

DELIMITER $$
USE `proyectodb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `InsertarUsuario`(
in PNombre       varchar(45), 
in PApellido varchar(45),
in PEmail   varchar(45),
in PContrasena   varchar(45),
in PImagen      varchar(45)
)
begin
insert into Usuarios (Nombre,Apellido,Email,Contrasena,Imagen)values (PNombre , PApellido,PEmail ,PContrasena,PImagen );
end$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure LoguearUsuario
-- -----------------------------------------------------

DELIMITER $$
USE `proyectodb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `LoguearUsuario`(
in PEmail       varchar(45), 
in PContrasena varchar(45)
)
begin
select Nombre,Apellido,Email,Contrasena from Usuarios where Email=PEmail and Contrasena=PContrasena;

end$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
